### ISSUE TITLE
Create .env file

### ISSUE THREAD

**Issue by veerleprins** [SharonV33/guess-that-album#3]
You put your KEY on GitHub itself. Next time, try to create an .env file and place your KEY in it, because this is sensitive information to have online! You can do this by installing the dotenv package and creating the .env file 😄  

https://github.com/SharonV33/guess-that-album/blob/8f44ad3b95122f484f530a1ee8c3b243f6470996/server.js#L26

**Comment by SharonV33** [comment]
nice!
